import { createHash } from "node:crypto";
import { insertObservations, prisma, type ObservationRow } from "@scout/db";

/**
 * Synthetic load data at the Phase 11 scale, written directly.
 *
 * Resolution is not run over the million rows: that is measured separately
 * on a bounded, realistic subset (`resolveSubset`), because the graph
 * reads are what the million is for. Entities and memberships are written
 * as a completed run would have left them, edges are drawn between random
 * pairs with real windows and evidence, and every row sits under one
 * authorization so the whole set can be removed afterwards.
 */

export const LOAD_AUTHORIZATION_ID = "auth_load_test";
export const LOAD_REFERENCE = "LOAD-TEST-0001";
export const LOAD_SOURCE_ID = "load-synth";
const DAY = 86_400_000;
const T0 = Date.UTC(2026, 5, 1);

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const FIRST = ["ana", "ben", "carla", "dev", "erin", "farid", "gia", "hugo", "ines", "jon", "kai", "lena", "marco", "nour", "olu", "pia", "quinn", "rosa", "sam", "tomasz", "uma", "vik", "wen", "xia", "yara", "zed"];
const LAST = ["abara", "berg", "castillo", "diaz", "eriksen", "ferreira", "garcia", "haddad", "ivanova", "jensen", "kim", "lindqvist", "moreau", "nowak", "okafor", "park", "quist", "rahman", "silva", "tanaka", "ueda", "varga", "weber", "xu", "young", "zhou"];
const CITIES: Array<[number, number]> = [[-122.68, 45.52], [-9.05, 53.27], [5.32, 60.39], [-71.62, -33.05], [139.69, 35.69], [28.98, 41.01], [-0.13, 51.51], [151.21, -33.87]];

export interface GenerateOptions {
  observations: number;
  entities: number;
  edges: number;
  seed?: number;
  log?: (line: string) => void;
}

export interface GenerateReport {
  caseId: string;
  authorizationId: string;
  observations: number;
  identifiers: number;
  entities: number;
  members: number;
  edges: number;
  seconds: Record<string, number>;
}

const stamp = () => performance.now();

export async function ensureLoadCase(): Promise<string> {
  const until = new Date(Date.now() + 365 * DAY);
  await prisma.authorization.upsert({
    where: { id: LOAD_AUTHORIZATION_ID },
    update: { validUntil: until, revokedAt: null },
    create: {
      id: LOAD_AUTHORIZATION_ID, reference: LOAD_REFERENCE, issuedBy: "load test",
      boundary: { scope: [{ kind: "identifier", value: "*" }], entityKinds: ["PERSON"] },
      sourceClasses: ["SENSOR", "PUBLIC_RECORD"], actionClasses: ["COLLECT", "RESOLVE", "READ_GRAPH"],
      validFrom: new Date(Date.now() - DAY), validUntil: until, createdBy: "load-test",
    },
  });
  await prisma.collectionSource.upsert({
    where: { id: LOAD_SOURCE_ID },
    update: {},
    create: { id: LOAD_SOURCE_ID, name: "Load test synthetic source", class: "SENSOR", licensingTerms: "Synthetic rows generated by the load test. No licence applies; there is nothing real here.", refreshCadenceSeconds: 1 },
  });
  const existing = await prisma.case.findFirst({ where: { authorizationRef: LOAD_REFERENCE } });
  if (existing !== null) return existing.id;
  const created = await prisma.case.create({
    data: { name: "Load Test", authorizationRef: LOAD_REFERENCE, authorizationId: LOAD_AUTHORIZATION_ID, notes: "Generated by apps/api/src/load. Every row is synthetic.", createdBy: "load-test" },
  });
  return created.id;
}

export async function generate(options: GenerateOptions): Promise<GenerateReport> {
  const log = options.log ?? (() => undefined);
  const rand = mulberry32(options.seed ?? 7);
  const int = (lo: number, hi: number) => lo + Math.floor(rand() * (hi - lo + 1));
  const pick = <T,>(xs: readonly T[]): T => xs[Math.floor(rand() * xs.length)] as T;
  const seconds: Record<string, number> = {};
  const caseId = await ensureLoadCase();

  // ── observations, in chunks, with identifiers ──
  let t = stamp();
  const perEntity = Math.max(1, Math.floor(options.observations / options.entities));
  let written = 0;
  let identifiers = 0;
  const memberRows: Array<{ entityId: string; observationId: string }> = [];
  const labels = new Map<string, string>();
  const CHUNK = 2_000;
  for (let start = 0; start < options.observations; start += CHUNK) {
    const rows: ObservationRow[] = [];
    const idRows: Array<{ observationId: string; kind: "NAME" | "EMAIL"; value: string; normalizedValue: string; normalizationVersion: string }> = [];
    for (let i = start; i < Math.min(options.observations, start + CHUNK); i += 1) {
      const entityIndex = Math.floor(i / perEntity) % options.entities;
      const entityId = `ent_load_${entityIndex}`;
      const first = FIRST[entityIndex % FIRST.length] as string;
      const last = LAST[Math.floor(entityIndex / FIRST.length) % LAST.length] as string;
      const name = `${first} ${last} ${entityIndex}`;
      labels.set(entityId, name);
      const [lon, lat] = pick(CITIES);
      const observedAt = new Date(T0 + int(0, 90) * DAY + int(0, 86_399) * 1000);
      const email = rand() < 0.6 ? `${first}.${last}${entityIndex}@example.net` : null;
      const normalized = { name, email, seq: i };
      const hash = createHash("sha256").update(JSON.stringify(normalized)).digest("hex");
      const id = `obs_load_${hash.slice(0, 20)}`;
      rows.push({
        id, sourceId: LOAD_SOURCE_ID, authorizationId: LOAD_AUTHORIZATION_ID, caseId, collectedAt: observedAt, observedAt,
        rawPayload: null, normalizedPayload: normalized, contentHash: hash,
        position: { lon: lon + (rand() - 0.5) * 0.2, lat: lat + (rand() - 0.5) * 0.2 }, confidenceBp: null, indeterminate: false, entityKind: "PERSON",
      });
      idRows.push({ observationId: id, kind: "NAME", value: name, normalizedValue: name, normalizationVersion: "load-1" });
      if (email !== null) idRows.push({ observationId: id, kind: "EMAIL", value: email, normalizedValue: email, normalizationVersion: "load-1" });
      memberRows.push({ entityId, observationId: id });
    }
    const ids = await insertObservations(rows);
    written += ids.length;
    const wrote = new Set(ids);
    const kept = idRows.filter((r) => wrote.has(r.observationId));
    for (let s = 0; s < kept.length; s += 5_000) await prisma.identifier.createMany({ data: kept.slice(s, s + 5_000), skipDuplicates: true });
    identifiers += kept.length;
    if ((start / CHUNK) % 50 === 0) log(`observations ${written.toLocaleString("en-US")} / ${options.observations.toLocaleString("en-US")}`);
  }
  seconds["observations"] = (stamp() - t) / 1000;

  // ── one completed run, the entities, the memberships ──
  t = stamp();
  const run = await prisma.resolutionRun.create({
    data: { authorizationId: LOAD_AUTHORIZATION_ID, status: "COMPLETE", finishedAt: new Date(), modelVersion: "load-synth", normalizationVersion: "load-1", matchThresholdBp: 9_500, reviewThresholdBp: 7_000, triggeredBy: "load-test" },
  });
  const entityRows = [...labels.entries()].map(([id, canonicalLabel]) => ({ id, kind: "PERSON" as const, canonicalLabel, status: "RESOLVED" as const, lastResolvedAt: new Date(), resolutionRunId: run.id }));
  for (let s = 0; s < entityRows.length; s += 5_000) await prisma.entity.createMany({ data: entityRows.slice(s, s + 5_000), skipDuplicates: true });
  const memberData = memberRows.map((m) => ({ entityId: m.entityId, observationId: m.observationId, scoreBp: 9_000, method: "load-synth", addedBy: "SYSTEM" as const }));
  for (let s = 0; s < memberData.length; s += 5_000) await prisma.entityMember.createMany({ data: memberData.slice(s, s + 5_000), skipDuplicates: true });
  seconds["entities"] = (stamp() - t) / 1000;

  // ── edges between random pairs, with windows and evidence ──
  t = stamp();
  const firstObservation = new Map<string, string>();
  for (const m of memberRows) if (!firstObservation.has(m.entityId)) firstObservation.set(m.entityId, m.observationId);
  const edgeRows = [];
  for (let k = 0; k < options.edges; k += 1) {
    const a = int(0, options.entities - 1);
    let b = int(0, options.entities - 1);
    if (b === a) b = (a + 1) % options.entities;
    const from = `ent_load_${a}`;
    const to = `ent_load_${b}`;
    const validFrom = new Date(T0 + int(0, 80) * DAY);
    const open = rand() < 0.7;
    edgeRows.push({
      fromEntityId: from, toEntityId: to, relation: rand() < 0.2 ? ("CO_LOCATED" as const) : ("ASSOCIATED_WITH" as const), validFrom,
      validUntil: open ? null : new Date(validFrom.getTime() + int(1, 10) * DAY), confidenceBp: 5_500, basis: "shared:ADDRESS",
      evidenceObservationIds: [firstObservation.get(from) as string, firstObservation.get(to) as string], authorizationId: LOAD_AUTHORIZATION_ID, fingerprint: `load|${k}`, createdBy: "load-test",
    });
  }
  for (let s = 0; s < edgeRows.length; s += 5_000) await prisma.entityEdge.createMany({ data: edgeRows.slice(s, s + 5_000), skipDuplicates: true });
  seconds["edges"] = (stamp() - t) / 1000;

  return { caseId, authorizationId: LOAD_AUTHORIZATION_ID, observations: written, identifiers, entities: entityRows.length, members: memberData.length, edges: edgeRows.length, seconds };
}

/**
 * Removes everything the load test wrote. The append-only triggers are
 * bypassed for this session only (superuser on the local Docker cluster),
 * which is the one place that is acceptable: rows that were never evidence.
 */
export async function clean(log: (line: string) => void = () => undefined): Promise<void> {
  const caseRow = await prisma.case.findFirst({ where: { authorizationRef: LOAD_REFERENCE } });
  await prisma.$transaction(async (tx) => {
    await tx.$executeRawUnsafe(`SET LOCAL session_replication_role = 'replica'`);
    const steps: Array<[string, string]> = [
      ["edges", `DELETE FROM "EntityEdge" WHERE "authorizationId" = '${LOAD_AUTHORIZATION_ID}'`],
      ["members", `DELETE FROM "EntityMember" WHERE "entityId" LIKE 'ent_load_%'`],
      ["entities", `DELETE FROM "Entity" WHERE "id" LIKE 'ent_load_%'`],
      ["runs", `DELETE FROM "ResolutionRun" WHERE "authorizationId" = '${LOAD_AUTHORIZATION_ID}'`],
      ["access log", `DELETE FROM "AccessLog" WHERE "authorizationId" = '${LOAD_AUTHORIZATION_ID}'`],
      ["identifiers", `DELETE FROM "Identifier" WHERE "observationId" LIKE 'obs_load_%'`],
      ["observations", `DELETE FROM "Observation" WHERE "authorizationId" = '${LOAD_AUTHORIZATION_ID}'`],
    ];
    for (const [name, sql] of steps) {
      const n = await tx.$executeRawUnsafe(sql);
      log(`removed ${n.toLocaleString("en-US")} ${name}`);
    }
    if (caseRow !== null) {
      await tx.$executeRawUnsafe(`DELETE FROM "AuditEvent" WHERE "caseId" = '${caseRow.id}'`);
      await tx.$executeRawUnsafe(`DELETE FROM "Case" WHERE "id" = '${caseRow.id}'`);
    }
    await tx.$executeRawUnsafe(`DELETE FROM "Authorization" WHERE "id" = '${LOAD_AUTHORIZATION_ID}'`);
  }, { timeout: 600_000 });
}
