/**
 * Synthetic resolution fixtures.
 *
 * About five hundred observations describing about a hundred and twenty
 * made-up entities, from three made-up sources, with every observation
 * carrying the entity it truly belongs to. No real person, vessel or aircraft
 * appears here: names are drawn from short lists, phones use the 555 exchange,
 * MMSIs and tail numbers are generated.
 *
 * Deterministic. The same seed produces the same rows and the same content
 * hashes, so the evaluation harness in services/resolution/eval can key its
 * expectations on hash rather than on ids the database assigns.
 *
 * The ground truth rides in `rawPayload._synthetic`. Normalizers and the
 * resolver never read `_synthetic`; the harness strips it before scoring.
 * Reading it would be cheating, and a test that lets the model cheat proves
 * nothing.
 */
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { PrismaClient } from "@prisma/client";
import { insertObservations, type ObservationRow } from "../src/fusion.js";

const prisma = new PrismaClient();
const SEED = 20260913;
const AUTHORIZATION_ID = "auth_synthetic_dev";
const NORMALIZATION_VERSION = "seed-naive-1";

// ── deterministic randomness ──────────────────────────────────────────────

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(SEED);
const pick = <T>(xs: readonly T[]): T => xs[Math.floor(rand() * xs.length)] as T;
const chance = (p: number): boolean => rand() < p;
const int = (lo: number, hi: number): number => lo + Math.floor(rand() * (hi - lo + 1));
const digits = (n: number): string => Array.from({ length: n }, () => String(int(0, 9))).join("");

// ── vocabulary ────────────────────────────────────────────────────────────

const FIRST = ["William", "Robert", "Elizabeth", "Michael", "James", "Jennifer", "Katherine", "Daniel", "Sarah", "Thomas", "Margaret", "Christopher", "Amara", "Wei", "Priya", "Mateo", "Yusuf", "Ingrid", "Tomasz", "Aiko", "Olu", "Nadia", "Sven", "Rosa", "Kenji", "Fatima", "Liam", "Zara", "Diego", "Hana"] as const;
const NICK: Record<string, string> = { William: "Bill", Robert: "Bob", Elizabeth: "Liz", Michael: "Mike", James: "Jim", Jennifer: "Jen", Katherine: "Kate", Daniel: "Dan", Thomas: "Tom", Margaret: "Meg", Christopher: "Chris" };
const LAST = ["Okafor", "Lindqvist", "Marchetti", "Nakamura", "Petrov", "Haddad", "Osei", "Brennan", "Castillo", "Varga", "Ferreira", "Kowalski", "Mbeki", "Sørensen", "Delgado", "Ivanova", "Tanaka", "Nowak", "Abara", "Quiroga", "Halvorsen", "Rahimi", "Duarte", "Eriksen", "Moreau"] as const;
const STREET = ["Harbor", "Maple", "Quarry", "Rafter", "Cedar", "Beacon", "Mill", "Summit", "Willow", "Granite"] as const;
const CITY = [
  { name: "Portland", lon: -122.676, lat: 45.523 },
  { name: "Halifax", lon: -63.573, lat: 44.649 },
  { name: "Galway", lon: -9.049, lat: 53.271 },
  { name: "Tromsø", lon: 18.955, lat: 69.649 },
  { name: "Valparaíso", lon: -71.628, lat: -33.047 },
  { name: "Kochi", lon: 76.267, lat: 9.931 },
] as const;
const DOMAIN = ["example.com", "example.org", "example.net", "mail.example"] as const;
const AIRCRAFT_TYPE = ["C172", "PA28", "B350", "C56X", "PC12"] as const;
const SOURCES = [
  { id: "synth-records", name: "Synthetic public records", class: "PUBLIC_RECORD", licensingTerms: "Synthetic fixture data generated by Scout. No licence applies; no real persons.", refreshCadenceSeconds: 86_400 },
  { id: "synth-sensor", name: "Synthetic sensor feed", class: "SENSOR", licensingTerms: "Synthetic fixture data generated by Scout. No licence applies; no real platforms.", refreshCadenceSeconds: 60 },
  { id: "synth-broker", name: "Synthetic broker extract", class: "BROKER", licensingTerms: "Synthetic fixture data generated by Scout. No licence applies; no real persons.", refreshCadenceSeconds: 3_600 },
] as const;

// ── canonical entities ────────────────────────────────────────────────────

interface Person { key: string; kind: "PERSON"; first: string; last: string; email: string; phone: string; address: string; handle: string; city: (typeof CITY)[number] }
interface Vessel { key: string; kind: "VESSEL"; name: string; mmsi: string; imo: string; callsign: string; lon: number; lat: number }
interface Aircraft { key: string; kind: "AIRCRAFT"; tail: string; icaoHex: string; type: string; lon: number; lat: number }
interface Org { key: string; kind: "ORG"; name: string; suffix: string; cik: string; ticker: string | null; city: (typeof CITY)[number] }
type Truth = Person | Vessel | Aircraft | Org;

function person(n: number, overrides: Partial<Person> = {}): Person {
  const first = pick(FIRST);
  const last = pick(LAST);
  const city = pick(CITY);
  return {
    key: `person-${String(n).padStart(3, "0")}`,
    kind: "PERSON",
    first,
    last,
    email: `${first}.${last}${int(1, 99)}@${pick(DOMAIN)}`.toLowerCase(),
    phone: `+1${pick(["415", "503", "902", "617"])}555${digits(4)}`,
    address: `${int(10, 999)} ${pick(STREET)} Street, ${city.name}`,
    handle: `@${first}${last}`.toLowerCase(),
    city,
    ...overrides,
  };
}

const truths: Truth[] = [];
for (let i = 1; i <= 84; i += 1) truths.push(person(i));
// Hard case A: three pairs of distinct people who share a full name.
for (let i = 0; i < 3; i += 1) {
  const a = person(85 + i * 2);
  truths.push(a, person(86 + i * 2, { first: a.first, last: a.last }));
}
for (let i = 1; i <= 20; i += 1) {
  const c = pick(CITY);
  truths.push({
    key: `vessel-${String(i).padStart(3, "0")}`,
    kind: "VESSEL",
    name: `${pick(["MV", "MT", "FV"])} ${pick(STREET)} ${pick(["Star", "Spirit", "Dawn", "Pride"])}`,
    mmsi: `${pick(["257", "316", "338", "725"])}${digits(6)}`,
    imo: `9${digits(6)}`,
    callsign: `${pick(["LA", "VC", "WD", "CB"])}${digits(2)}${pick(["K", "Q", "Z"])}`,
    lon: c.lon + (rand() - 0.5) * 2,
    lat: c.lat + (rand() - 0.5) * 2,
  });
}
const ORG_WORDS = ["Acme", "Beacon", "Granite", "Harbor", "Quarry", "Summit", "Willow", "Meridian", "Cedar", "Northwind", "Fulcrum", "Lantern", "Rafter", "Sluice", "Anvil"] as const;
const ORG_KINDS = ["Holdings", "Logistics", "Maritime", "Systems", "Partners", "Energy"] as const;
const SUFFIXES = ["Inc", "LLC", "Ltd", "Corp"] as const;
for (let i = 1; i <= 15; i += 1) {
  truths.push({
    key: `org-${String(i).padStart(3, "0")}`,
    kind: "ORG",
    name: `${ORG_WORDS[(i - 1) % ORG_WORDS.length] as string} ${pick(ORG_KINDS)}`,
    suffix: pick(SUFFIXES),
    cik: String(int(1000, 1999999)).padStart(10, "0"),
    ticker: chance(0.5) ? `${(ORG_WORDS[(i - 1) % ORG_WORDS.length] as string).slice(0, 3).toUpperCase()}${pick(["X", "Q", "Z", ""])}` : null,
    city: pick(CITY),
  });
}
for (let i = 1; i <= 10; i += 1) {
  const c = pick(CITY);
  truths.push({
    key: `aircraft-${String(i).padStart(3, "0")}`,
    kind: "AIRCRAFT",
    tail: `N${digits(3)}${pick(["AB", "CD", "SK", "TQ"])}`,
    icaoHex: `a${digits(5)}`,
    type: pick(AIRCRAFT_TYPE),
    lon: c.lon + (rand() - 0.5),
    lat: c.lat + (rand() - 0.5),
  });
}

// ── noise ─────────────────────────────────────────────────────────────────

function nameVariant(p: Person): { first: string; last: string } {
  const r = rand();
  if (r < 0.25 && NICK[p.first] !== undefined) return { first: NICK[p.first] as string, last: p.last };
  if (r < 0.4) return { first: `${p.first[0]}.`, last: p.last };
  if (r < 0.55) return { first: p.first.toUpperCase(), last: p.last.toUpperCase() };
  if (r < 0.65 && p.last.length > 4) return { first: p.first, last: p.last.slice(0, 3) + p.last.slice(4) };
  return { first: p.first, last: p.last };
}
function emailVariant(email: string): string {
  const [local, host] = email.split("@") as [string, string];
  const r = rand();
  if (r < 0.3) return `${local.replace(/\./g, "")}@${host}`;
  if (r < 0.5) return `${local}+news@${host}`;
  if (r < 0.7) return email.toUpperCase();
  return email;
}
function phoneVariant(e164: string): string {
  const d = e164.slice(2);
  const r = rand();
  if (r < 0.3) return `(${d.slice(0, 3)}) ${d.slice(3, 6)}-${d.slice(6)}`;
  if (r < 0.5) return `${d.slice(0, 3)}.${d.slice(3, 6)}.${d.slice(6)}`;
  if (r < 0.7) return `+1 ${d.slice(0, 3)} ${d.slice(3, 6)} ${d.slice(6)}`;
  return e164;
}
function addressVariant(a: string): string {
  const r = rand();
  if (r < 0.4) return a.replace(" Street,", " St,");
  if (r < 0.6) return `${a.split(",")[0] as string} Apt ${int(1, 30)},${a.split(",")[1] as string}`;
  return a;
}
const jitter = (v: number, by: number): number => v + (rand() - 0.5) * by;

// ── observations ──────────────────────────────────────────────────────────

const naive = (v: string): string => v.trim().toLowerCase();
const phoneDigits = (v: string): string => v.replace(/\D/g, "").replace(/^1(\d{10})$/, "$1");

interface Extracted { kind: string; value: string; normalizedValue: string }
interface Built { row: ObservationRow; identifiers: Extracted[]; truthKey: string; kind: Truth["kind"]; note?: string }

function canonicalJson(value: unknown): string {
  const sort = (v: unknown): unknown =>
    Array.isArray(v) ? v.map(sort)
    : v !== null && typeof v === "object"
      ? Object.fromEntries(Object.keys(v as Record<string, unknown>).sort().map((k) => [k, sort((v as Record<string, unknown>)[k])]))
      : v;
  return JSON.stringify(sort(value));
}
const hashOf = (normalized: Record<string, unknown>): string =>
  createHash("sha256").update(canonicalJson(normalized), "utf8").digest("hex");

const T0 = Date.UTC(2026, 5, 1);
const observedAt = (): Date => new Date(T0 + int(0, 90) * 86_400_000 + int(0, 86_399) * 1000);

function build(sourceId: string, truth: Truth, normalized: Record<string, unknown>, identifiers: Extracted[], position: { lon: number; lat: number } | null, note?: string): Built {
  const observed = observedAt();
  const raw = { ...normalized, _synthetic: { truthKey: truth.key, kind: truth.kind, ...(note === undefined ? {} : { note }) } };
  const row: ObservationRow = {
    sourceId,
    authorizationId: AUTHORIZATION_ID,
    collectedAt: new Date(observed.getTime() + int(1, 3600) * 1000),
    observedAt: observed,
    rawPayload: raw,
    normalizedPayload: normalized,
    contentHash: hashOf(normalized),
    position,
    confidenceBp: chance(0.8) ? int(6000, 10_000) : null,
    indeterminate: false,
    entityKind: truth.kind,
  };
  return { row, identifiers, truthKey: truth.key, kind: truth.kind, ...(note === undefined ? {} : { note }) };
}

const built: Built[] = [];

for (const t of truths) {
  if (t.kind === "PERSON") {
    const n = int(3, 6);
    for (let i = 0; i < n; i += 1) {
      const src = pick(["synth-records", "synth-broker", "synth-broker", "synth-sensor"] as const);
      const name = nameVariant(t);
      const pos = src === "synth-sensor" || chance(0.3) ? { lon: jitter(t.city.lon, 0.04), lat: jitter(t.city.lat, 0.04) } : null;
      if (src === "synth-records") {
        const address = addressVariant(t.address);
        const normalized = { name: `${name.first} ${name.last}`, address, city: t.city.name, documentNo: chance(0.5) ? `DOC-${digits(7)}` : undefined };
        built.push(build(src, t, normalized, [
          { kind: "NAME", value: normalized.name, normalizedValue: naive(normalized.name) },
          { kind: "ADDRESS", value: address, normalizedValue: naive(address) },
        ], pos));
      } else if (src === "synth-broker") {
        const email = emailVariant(t.email); const phone = phoneVariant(t.phone);
        const normalized = { name: `${name.first} ${name.last}`, email, phone, handle: chance(0.6) ? t.handle : undefined };
        built.push(build(src, t, normalized, [
          { kind: "NAME", value: normalized.name, normalizedValue: naive(normalized.name) },
          { kind: "EMAIL", value: email, normalizedValue: naive(email) },
          { kind: "PHONE", value: phone, normalizedValue: phoneDigits(phone) },
          ...(normalized.handle === undefined ? [] : [{ kind: "HANDLE", value: normalized.handle, normalizedValue: naive(normalized.handle) }]),
        ], pos));
      } else {
        const phone = phoneVariant(t.phone);
        const normalized = { deviceId: `dev-${createHash("sha1").update(t.key).digest("hex").slice(0, 10)}`, phone, seenNear: t.city.name };
        built.push(build(src, t, normalized, [
          { kind: "DEVICE_ID", value: normalized.deviceId, normalizedValue: normalized.deviceId },
          { kind: "PHONE", value: phone, normalizedValue: phoneDigits(phone) },
        ], pos));
      }
    }
  } else if (t.kind === "VESSEL") {
    const n = int(3, 5);
    for (let i = 0; i < n; i += 1) {
      const src = pick(["synth-sensor", "synth-sensor", "synth-records"] as const);
      const mmsi = t.key === "vessel-007" && i === 0 ? `${t.mmsi.slice(0, 8)}${(Number(t.mmsi[8]) + 1) % 10}` : t.mmsi;
      const note = mmsi === t.mmsi ? undefined : "hard: mmsi off by one digit; expect REVIEW or INDETERMINATE";
      const normalized = src === "synth-sensor"
        ? { mmsi, name: chance(0.7) ? t.name : t.name.toUpperCase(), sog: int(0, 20), cog: int(0, 359) }
        : { name: t.name, imo: t.imo, callsign: t.callsign, flag: pick(["NO", "CA", "IE", "CL"]) };
      const ids: Extracted[] = [{ kind: "NAME", value: t.name, normalizedValue: naive(t.name) }];
      if ("mmsi" in normalized) ids.push({ kind: "MMSI", value: mmsi, normalizedValue: mmsi });
      if ("imo" in normalized) ids.push({ kind: "IMO", value: t.imo, normalizedValue: t.imo });
      built.push(build(src, t, normalized, ids, src === "synth-sensor" ? { lon: jitter(t.lon, 0.5), lat: jitter(t.lat, 0.5) } : null, note));
    }
  } else if (t.kind === "ORG") {
    const n = int(3, 5);
    const LONG: Record<string, string> = { Inc: "Incorporated", LLC: "L.L.C.", Ltd: "Limited", Corp: "Corporation" };
    for (let i = 0; i < n; i += 1) {
      const src = pick(["synth-records", "synth-records", "synth-broker"] as const);
      const r = rand();
      const name =
        r < 0.3 ? `${t.name} ${t.suffix}`
        : r < 0.5 ? `${t.name.toUpperCase()}, ${t.suffix.toUpperCase()}.`
        : r < 0.7 ? `${t.name} ${LONG[t.suffix] as string}`
        : r < 0.85 ? t.name
        : `${t.name} ${t.suffix}.`;
      const normalized = src === "synth-records"
        ? { title: name, cik: chance(0.8) ? t.cik : undefined, ticker: t.ticker ?? undefined, jurisdiction: "US", city: t.city.name }
        : { name, ticker: t.ticker ?? undefined, city: t.city.name, domain: `${t.name.split(" ")[0]?.toLowerCase() as string}.example` };
      const ids: Extracted[] = [{ kind: "NAME", value: name, normalizedValue: naive(name) }];
      if ("cik" in normalized && normalized.cik !== undefined) ids.push({ kind: "DOCUMENT_NO", value: `CIK${t.cik}`, normalizedValue: `CIK${t.cik}` });
      if ("domain" in normalized) ids.push({ kind: "DOMAIN", value: normalized.domain, normalizedValue: normalized.domain });
      built.push(build(src, t, normalized, ids, null));
    }
  } else {
    const n = int(3, 4);
    for (let i = 0; i < n; i += 1) {
      const src = pick(["synth-sensor", "synth-records"] as const);
      const normalized = src === "synth-sensor"
        ? { icaoHex: t.icaoHex, callsign: chance(0.5) ? t.tail : undefined, altitudeFt: int(1000, 41_000) }
        : { tail: t.tail, type: t.type, icaoHex: chance(0.5) ? t.icaoHex.toUpperCase() : undefined };
      const ids: Extracted[] = [];
      if (normalized.icaoHex !== undefined) ids.push({ kind: "ICAO_HEX", value: normalized.icaoHex, normalizedValue: naive(normalized.icaoHex) });
      if ("tail" in normalized) ids.push({ kind: "TAIL_NUMBER", value: t.tail, normalizedValue: t.tail.toUpperCase() });
      built.push(build(src, t, normalized, ids, src === "synth-sensor" ? { lon: jitter(t.lon, 1), lat: jitter(t.lat, 1) } : null));
    }
  }
}

// ── write ─────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const now = new Date();
  await prisma.authorization.upsert({
    where: { id: AUTHORIZATION_ID },
    update: {},
    create: {
      id: AUTHORIZATION_ID,
      reference: "SYNTHETIC-DEV-0001",
      issuedBy: "Scout fixture generator (synthetic data; no real persons or platforms)",
      boundary: { scope: [], entityKinds: [] },
      sourceClasses: ["PUBLIC_RECORD", "SENSOR", "BROKER"],
      // BIOMETRIC_COMPARE too: the synthetic case is the sandbox for the
      // recognition screen, against a gallery of made-up people.
      actionClasses: ["COLLECT", "RESOLVE", "READ_GRAPH", "BIOMETRIC_COMPARE"],
      validFrom: new Date(now.getTime() - 86_400_000),
      validUntil: new Date(now.getTime() + 10 * 365 * 86_400_000),
      createdBy: "seed-v2",
    },
  });

  // A case for the fixtures, so the console and the v2 routes can reach them.
  // Named so nobody mistakes it for an engagement.
  const existingCase = await prisma.case.findFirst({ where: { authorizationRef: "SYNTHETIC-DEV-0001" } });
  const fixtureCase =
    existingCase !== null
      ? await prisma.case.update({ where: { id: existingCase.id }, data: { authorizationId: AUTHORIZATION_ID } })
      : await prisma.case.create({
          data: {
            name: "Synthetic Fixtures",
            authorizationRef: "SYNTHETIC-DEV-0001",
            authorizationId: AUTHORIZATION_ID,
            notes: "Generated by packages/db/prisma/seed-v2.ts. Every person, vessel, aircraft and company here is made up.",
            createdBy: "seed-v2",
          },
        });
  for (const b of built) b.row.caseId = fixtureCase.id;

  for (const s of SOURCES) {
    await prisma.collectionSource.upsert({
      where: { id: s.id },
      update: {},
      create: { id: s.id, name: s.name, class: s.class, licensingTerms: s.licensingTerms, refreshCadenceSeconds: s.refreshCadenceSeconds },
    });
  }

  // Deterministic ids, so a re-run is a no-op rather than a duplicate set.
  for (const b of built) b.row.id = `obs_${b.row.contentHash.slice(0, 24)}`;
  const written = new Set(await insertObservations(built.map((b) => b.row)));

  const identifierRows = built
    .filter((b) => written.has(b.row.id as string))
    .flatMap((b) => b.identifiers.map((i) => ({
      observationId: b.row.id as string,
      kind: i.kind as never,
      value: i.value,
      normalizedValue: i.normalizedValue,
      normalizationVersion: NORMALIZATION_VERSION,
    })));
  if (identifierRows.length > 0) await prisma.identifier.createMany({ data: identifierRows });

  // The harness's copy. Keyed on contentHash, never on database ids.
  const here = dirname(fileURLToPath(import.meta.url));
  const out = resolve(here, "../../../services/resolution/eval/fixtures");
  mkdirSync(out, { recursive: true });
  const byKey = new Map<string, number>();
  for (const b of built) byKey.set(b.truthKey, (byKey.get(b.truthKey) ?? 0) + 1);
  writeFileSync(
    resolve(out, "synthetic.json"),
    JSON.stringify(
      {
        generatedBy: "packages/db/prisma/seed-v2.ts",
        seed: SEED,
        normalizationVersion: NORMALIZATION_VERSION,
        entities: truths.map((t) => ({ truthKey: t.key, kind: t.kind, observations: byKey.get(t.key) ?? 0 })),
        // Payload and identifiers ride along so the harness needs no database:
        // it resolves from this file alone and scores against truthKey.
        observations: built.map((b) => ({
          id: b.row.id,
          contentHash: b.row.contentHash,
          sourceId: b.row.sourceId,
          truthKey: b.truthKey,
          kind: b.kind,
          observedAt: b.row.observedAt.toISOString(),
          position: b.row.position,
          payload: b.row.normalizedPayload,
          identifiers: b.identifiers.map((i) => ({ kind: i.kind, value: i.value })),
          ...(b.note === undefined ? {} : { note: b.note }),
        })),
        hardCases: {
          sharedFullName: truths.filter((t) => t.kind === "PERSON" && Number(t.key.slice(-3)) >= 85).map((t) => t.key),
          mmsiOffByOne: ["vessel-007"],
        },
      },
      null,
      2,
    ),
  );

  console.log(`seed-v2: ${truths.length} entities, ${built.length} observations built, ${written.size} written, ${identifierRows.length} identifiers`);
}

main()
  .catch((error: unknown) => {
    console.error("seed-v2 failed:", error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
